OE-10484 - mean deviation and visual field index is now extracted from the HFA file to OE
openeyes/PayloadProcessor pull request #51
Opened 2020-10-09 00:42 UTC by preet90

2020-10-09 07:43 UTC, justulka requested changes

2020-10-09 07:43 UTC, justulka commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
>  addRoutine('GENERIC_EXTRACT_PDF');
@preet90 We're only doing Light Integration now, what is this for?

2020-10-09 07:43 UTC, justulka commented on src/main/resources/routineLibrary/create_event
> +        deviceInformationRow.visual_field_index = requestData.visual_field_index;
This is device information table which is generic to all the devices,  report type specific information shouldn't be stored there.

2020-10-09 07:45 UTC, justulka commented on src/main/resources/routineLibrary/create_event
> +        deviceInformationRow.visual_field_index = requestData.visual_field_index;
Payload Processor is being used in Bolton and this change could result with an error, unless you're doing the migration from 3.5.1?

2020-10-09 23:35 UTC, preet90 commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
>  addRoutine('GENERIC_EXTRACT_PDF');
Could you please care to expand on the Light Integration part? I am not aware of that.

The extraction of the mean_deviation and visual_field_index values from the report are required to complete the dev work for the https://openeyes.atlassian.net/browse/OE-9567 ticket.

2020-10-12 13:47 UTC, justulka commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
>  addRoutine('GENERIC_EXTRACT_PDF');
As far as i am aware we're not doing any data extraction right now and we call it Light Integration ,where we only extract media and attach to events or create events the extracted images.

OE-9567 is "NEW" status why it's being worked on? Same as OE-10484.

I cannot accept the current approach as the device information model was not made for value extractions.

We do have an OCT element where we could extract some values and input  it there, but im not sure if this will suit the purpose if this is not an OCT event.

OE PR for OE-10484 is for develop, payload processor is being used in other trusts and this change will break there.

2020-10-12 13:56 UTC, justulka commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
>  addRoutine('GENERIC_EXTRACT_PDF');
If you're adding new fields/functionality to payloadProcessor , could the requirements first be discussed with me to make sure our views align?

Is a new element required for this work? Could the front-end for OpenEyes side be decided first and then we can take a look at inputting the values?

2020-10-13 01:10 UTC, gmorph-work commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
>  addRoutine('GENERIC_EXTRACT_PDF');
@justulka - OE-9567 is in New because the way JIRA is setup means I'm the only person at TKL that can transition the stupid things out of that state and I hadn't gotten to it.
Light integration as you call it I believe is for Pennine only.  This work is for VF integration which is the DAs No 1 priority for TKL in the December release so we need to get this work going.
We need to store data associated with images - that is mandatory moving forward.  We will send through a design - be great if you could review and provide feedback.

2020-10-13 08:59 UTC, justulka commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
>  addRoutine('GENERIC_EXTRACT_PDF');
@gmorph-work  Thanks i understand the situation better now. Will take a look

2020-10-21 11:03 UTC, preet90 commented
Created a new PR (https://github.com/openeyes/PayloadProcessor/pull/54) to merge these changes into develop branch instead of master branch because of a newly created table on the OE side that exists only in the develop branch.

2020-10-22 21:09 UTC, closed without merging

2020-10-22 21:09 UTC, preet90 commented
Created a new PR (#54) to merge these changes into develop branch instead of master branch because of a newly created table on the OE side that exists only in the develop branch.