Feature/pennine device work anterion
openeyes/PayloadProcessor pull request #53
Opened 2020-10-21 09:54 UTC by justulka

2020-10-26 21:42 UTC, preet90 commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
> +requestData.event_subtype = "Visual Field Images";
This will override the changes made in OE-10243 ticket. Confirm if this is required.

2020-10-26 21:42 UTC, preet90 commented on src/main/resources/routineLibrary/Quantel_Medical
> +requestData.report_type = "B SCAN Images";
Also, won't this change affect the current deployments of the payload processor?

2020-10-26 21:42 UTC, preet90 commented on src/main/resources/routineLibrary/Heidelberg_Engineering_OPT
> +addRoutine('GENERIC_SET_ATTACHMENT_TYPE');
Both the routine libraries (Heidelberg_Engineering_OP and Heidelberg_Engineering_OPT) are the same - do we really need two different routine libraries if they are doing the exact same thing? Can they be made more reusable?

2020-10-27 08:27 UTC, justulka commented on src/main/resources/routineLibrary/Quantel_Medical
> +requestData.report_type = "B SCAN Images";
Currently the only LIVE system that is using Payload Processor is Bolton where we only receive IOLmaster's all other devices are not used.

2020-10-27 08:34 UTC, justulka commented on src/main/resources/routineLibrary/Heidelberg_Engineering_OPT
> +addRoutine('GENERIC_SET_ATTACHMENT_TYPE');
It's either having an if statement before adding modality specific routines that would route to one routine or having two routine files.

Having separate files also makes modification easier to a specific report without changing code too much after we would receive a variety of different reports and would be confident that they both of these reports can re-use the same routine we can revisit this. I only had a few files to work with , so this will make the testing easier after we receive a big batch of them.

2020-10-27 08:38 UTC, justulka commented on src/main/resources/routineLibrary/Carl_Zeiss_Meditec_OPV
> +requestData.event_subtype = "Visual Field Images";
This will be done for 3.6.1/3.5.1 your changes will be in develop and you will need to remake this change on payloadprocessor:develop or just use "Visual Field Images". Pennine said they want to name it "Visual Field Images" and that's the migrations that we're done, this is an easy change that we can solve.

2020-10-28 04:23 UTC, gmorph-work commented
Is this work associated with a JIRA?  If not can we please raise a JIRA for this work?  I had understood that the branching naming strategy was to have the JIRA number in it so people could see what the work was for.

2020-10-28 09:02 UTC, justulka commented
@gmorph-work  https://openeyes.atlassian.net/browse/OE-10507

2020-10-29 03:24 UTC, preet90 commented on src/main/resources/routineLibrary/GENERIC_MANUFACTURER_RAW
> +addRoutine('GENERIC_SET_ATTACHMENT_TYPE');
GENERIC_MANUFACTURER_RAW routine library is not getting called anywhere. What's the use of this?

Why is this called GENERIC and have calls to the other routines that are specific for the machine i.e. Heidelberg

2020-10-29 07:58 UTC, justulka commented on src/main/resources/routineLibrary/GENERIC_MANUFACTURER_RAW
> +addRoutine('GENERIC_SET_ATTACHMENT_TYPE');
It is called from the default routine path

DICOM_SEED Line:47

As the manufacturer data is not in the dicom headers it doesn't find a DEVICE_Manufacturer specific routine it goes to a "GENERIC" manufacturer which is a manufacturer that was not found for that Modality.

And as mentioned previously i only had a few files to work with and i might have or might not receive additional data when more files are coming in and can re-visit the routine names when i will be more confident in the data i receive.

2020-11-01 23:23 UTC, gmorph-work commented
@harikulendran - Hi Hari.  Are you able to review this please so we can get it merged in.  The client is waiting is waiting on this functionality.

2020-11-02 10:03 UTC, harikulendran requested changes

2020-11-02 10:25 UTC, justulka commented on src/main/java/com/abehrdigital/payloadprocessor/utils/PDFUtils.java
>              throw ex;
Cannot comment on the pdfUtils part, it was done in the beginning and needs revisiting and refactoring when we start using it properly.

2020-11-02 11:14 UTC, harikulendran commented on src/main/java/com/abehrdigital/payloadprocessor/utils/PDFUtils.java
>              throw ex;
okay fair enough

2020-11-02 11:14 UTC, harikulendran approved these changes

2020-11-04 12:29 UTC, merged