OE-10484 Import VFI and MD values from HFA
openeyes/PayloadProcessor pull request #54
Opened 2020-10-21 11:00 UTC by preet90

Created this PR to merge the changes into the develop branch (instead of the master branch) because the OE-10484 ticket is for the develop branch in OE.

Changes in this PR

- Merged the master branch into develop branch. 
- Added an Eye Dao to get the id of the eye for the laterality, created a supporting information text object to store the data that gets saved into the newly created supporting information element table as well as the supporting information details table.

2020-10-22 07:09 UTC, justulka requested changes

2020-10-22 07:09 UTC, justulka commented on src/main/java/com/abehrdigital/payloadprocessor/dao/EyeDao.java
> +}
The eye_id's never change and you can create a similar class as we have in OpenEyes which has constants for the EYE_SIDE => ID

2020-10-22 07:09 UTC, justulka commented on src/main/resources/routineLibrary/create_event
> +
You're using this routine for a specific event creation and therefore should require a new routine

2020-10-22 07:09 UTC, justulka commented on src/main/resources/routineLibrary/create_event
> +
As mentioned in PHP PR, i don't like and would not like to see the key => value table here , but a specific HFA element, not a generic "supporting information"

2020-10-22 07:46 UTC, preet90 commented on src/main/resources/routineLibrary/create_event
> +
Just wondering what sort of columns should be a part of this HFA element data model.

2020-10-22 07:48 UTC, justulka commented on src/main/resources/routineLibrary/create_event
> +
mean_deviation  and visual_field_index , that's all you have right now from my understanding and therefore should be the only columns

2020-10-27 15:08 UTC, justulka requested changes

2020-10-27 15:08 UTC, justulka commented on src/main/resources/routineLibrary/create_hfa_event
> +var eventSubtype = "OCT";
the eventSubType should from requestData as this will override it

2020-10-27 15:08 UTC, justulka commented on src/main/resources/routineLibrary/create_hfa_event
> +                }
This is for assessment , this needs changing

2020-10-27 15:08 UTC, justulka commented on src/main/resources/routineLibrary/create_hfa_event
> +var hfaData = bindTextObject('HFA_DATA');
Use requestData

2020-10-27 15:08 UTC, justulka commented on src/main/resources/routineLibrary/create_hfa_event
> +            }
Use requestData as in the assessment.

2020-10-28 03:55 UTC, preet90 commented on src/main/resources/routineLibrary/create_hfa_event
> +            }
I have used the same pattern as in the assessment routines - 
create_assessment_event uses the assessmentData and not the requestData unless I am looking at the wrong place.

`var assessmentData = bindTextObject('ASSESSMENT_DATA');
`
```
if (dataSet == "ophgeneric_assessment_entry") {
        if (requestData.eyeId !== 3) {
            var assessmentReportRow = data.$$_ROW_$$[0];
            for (assessmentDataKey in assessmentData) {
                assessmentReportRow[assessmentDataKey] = assessmentData[assessmentDataKey];
                abac_json[assessmentDataKey] = "RO";
            }
            assessmentReportRow.eye_id = requestData.eyeId;
            assessmentReportRow.abac_json = abac_json;
            data.$$_ROW_$$[1] = {};
        }

    }
```

2020-10-28 03:58 UTC, preet90 commented on src/main/resources/routineLibrary/create_hfa_event
> +                }
Updated this.

2020-10-28 04:06 UTC, preet90 commented on src/main/resources/routineLibrary/create_hfa_event
> +var eventSubtype = "OCT";
Removed this as the eventsubtype get set later in the routine from the requestData.

2020-10-28 04:07 UTC, preet90 commented
Please look at my last comment regarding the HFA_DATA text object similar to the ASSESSMENT_DATA text object.

2020-10-28 09:16 UTC, justulka commented on src/main/resources/routineLibrary/create_hfa_event
> +            }
I see, forgot about that. I think then it's fine you can keep it that way

2020-10-29 05:25 UTC, preet90 commented
@justulka Could you please merge this code into the develop branch. Thanks.

2020-10-29 08:16 UTC, merged